amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.05
    update_min_d: 0.1
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    #set_initial_pose: True
    #initial_pose:
    #  x: 10.35
    #  y: 51.776
    #  z: 0.0
    #  yaw: -0.625

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator:
  ros__parameters:
    use_sim_time: True
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20
    controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    controller_plugin_ids: ["DynamicFollowPath"]
    DynamicFollowPath.footprint_model.type: circular
    DynamicFollowPath.footprint_model.radius: 0.28
    DynamicFollowPath.min_obstacle_dist: 0.1
    DynamicFollowPath.inflation_dist: 0.1
    DynamicFollowPath.costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
    DynamicFollowPath.costmap_converter_spin_thread: True
    DynamicFollowPath.costmap_converter_rate: 15
    DynamicFollowPath.enable_homotopy_class_planning: True
    DynamicFollowPath.enable_multithreading: True
    #DynamicFollowPath.weight_obstacle: 100.0
    DynamicFollowPath.optimization_verbose: False
    DynamicFollowPath.teb_autoresize: True
    DynamicFollowPath.min_samples: 3
    DynamicFollowPath.max_samples: 20
    DynamicFollowPath.max_global_plan_lookahead_dist: 1.0
    DynamicFollowPath.visualize_hc_graph: True
    DynamicFollowPath.max_vel_x: 0.46
    DynamicFollowPath.max_vel_theta: 1.5
    DynamicFollowPath.acc_lim_x: 1.0
    DynamicFollowPath.acc_lim_theta: 2.5

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      robot_radius: 0.25
      inflation_layer:
        cost_scaling_factor: 3.0
      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      robot_base_frame: base_link
      global_frame: map
      use_sim_time: True
      plugin_names: [
        "static_layer",
        "obstacle_layer",
        "stvl_layer",
        "inflation_layer"]
      plugin_types: [
        "nav2_costmap_2d::StaticLayer",
        "nav2_costmap_2d::ObstacleLayer",
        "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer",
        "nav2_costmap_2d::InflationLayer"]
      robot_radius: 0.25
      resolution: 0.05
      stvl_layer:
        enabled: True
        voxel_decay: 15.0
        decay_model: 0
        voxel_size: 0.1
        track_unknown_space: True
        max_obstacle_height: 2.0
        unknown_threshold: 15
        mark_threshold: 0
        update_footprint_enabled: True
        combination_method: 1
        obstacle_range: 2.0
        origin_z: 0.0
        publish_voxel_map: False
        transform_tolerance: 1.0
        mapping_mode: False
        map_save_duration: 60.0
        observation_sources: pointcloud
        pointcloud:
          data_type: PointCloud2
          topic: /xtion/depth/points
          marking: True
          clearing: True
          min_obstacle_height: 0.15
          max_obstacle_height: 2.0
          expected_update_rate: 2.0
          observation_persistence: 0.0
          inf_is_valid: False
          voxel_filter: False
          clear_after_reading: True
          max_z: 7.0
          min_z: 0.15
          vertical_fov_angle: 0.8745
          horizontal_fov_angle: 1.048
          decay_acceleration: 15.0
          model_type: 0

      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      inflation_layer:
        cost_scaling_factor: 5.0
        inflation_radius:     1.0
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "turtlebot3_world.yaml"

planner_server:
  ros__parameters:
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]
    planner_plugin_ids: ["GridBased"]
    use_sim_time: True
    GridBased.tolerance: 10.0
    GridBased.use_astar: true
    GridBased.allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

robot_state_publisher:
  ros__parameters:
    use_sim_time: True
